;
; File generated by cc65 v 2.16 - Ubuntu 2.16-2
;
	.fopt		compiler,"cc65 v 2.16 - Ubuntu 2.16-2"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_ppu_on_all
	.export		_main

.segment	"BSS"

.segment	"BSS"
_x:
	.res	1,$00
.segment	"BSS"
_y:
	.res	1,$00
.segment	"BSS"
_z:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldx     #$00
	lda     #$64
	sta     _x
	ldx     #$00
	lda     #$02
	sta     _y
	ldx     #$00
	lda     _x
	jsr     pushax
	ldx     #$00
	lda     _y
	jsr     tosudivax
	ldx     #$00
	sta     _z
	jsr     _ppu_on_all
	jmp     L000B
L000B:	jmp     L000B
	rts

.endproc

